### PR TITLE
Additional python3 fixes

### PR DESCRIPTION
**Pull request by blueyed**
With this, all of my plugins work (including UltiSnips, YouCompleteMe/Jedi).

### CODE REVIEW

**Comment by Shougo** [comment]
Thank you.  I merged it.

**Comment by Shougo** [comment]
Please check your patch.
if_python3 does not work.
I may rever these patches.

**Comment by blueyed** [comment]
> if_python3 does not work.

Do you mean :py3 in general?
Are you using python3 or python for the binary?

**Comment by blueyed** [comment]
@Shougo 
Can you please answer my questions above? I'll look into it then.

**Comment by Shougo** [comment]
> Do you mean :py3 in general?

Yes.

> Are you using python3 or python for the binary?

No.  I don't check the plugins behavior.

**Comment by Shougo** [comment]
Please check `:py print(2)` and `:py3 print(2)` in your branch.
I tested it, but `:py3 print(2)` was just ignored.

**Pull request merged**
