### PR TITLE
WIP: travis: try python3-dev for pip3

### PR DESCRIPTION
**Pull request by blueyed**
Python3 on Travis, for #2208.

Ref: https://github.com/neovim/neovim/pull/2208#discussion_r27351248

Builds: https://travis-ci.org/blueyed/neovim

Please note that the `osx` OS does not appear to be supported here (in the fork(s)); see http://docs.travis-ci.com/user/multi-os/

### CODE REVIEW

**Comment by blueyed** [comment]
While the job list says "Python 3.4", it does not seem to be available (as `python` at least):
https://travis-ci.org/blueyed/neovim/builds/56278278

(also not available as `python3`: https://travis-ci.org/blueyed/neovim/jobs/56310067)

I've emailed the Travis support, hopefully they can help us.

**Comment by Shougo** [comment]
Thank you.  It seems good.

**Comment by blueyed** [comment]
I've got more information from the Travis support:

> First, keep in mind that the choice of the `language` value is not arbitrary. It has some profound effects, including the choice of VM image and how the build matrix is expanded. For "c", it means the "Ruby" VM image (since Ruby is the default) and only "env" and "compiler" values are considered for constructing the build matrix (see http://docs.travis-ci.com/user/languages/c/#Build-Matrix).
> 
> Second, multi-os feature is not generally available yet, so use of "os" has no effect if the feature is not enabled on the repository.
> 
> In general, if you have requirements involving multiple languages, it is a good idea to choose the language that gives the most "stuff". In your case, "python" has various Python runtimes, as well as compilers, pre-installed. It will not allow matrix expansion on "compiler", but I believe you can just set environment variable "CC", or call the compiler ("gcc" or "clang") directly.
> 
> Having said that, this is at odds with the multi-os feature (see https://github.com/travis-ci/travis-ci/issues/2312), which does not work with "language: python" at the moment. This may or may not be a deal breaker for you.
> 
> The next build environment update will include Python 3.2.3 on all Linux images (http://docs.travis-ci.com/user/build-environment-updates/2015-04-09). If this is sufficient, you can live with "language: c", and invoke "python3" where you need it. If not, installing Python 3.4 on demand might be a viable alternative.

**Comment by blueyed** [comment]
Closing this in favor of https://github.com/neovim/neovim/issues/2433.

**Pull request closed without merging**
